### ISSUE TITLE
why not to use Raspberry Pi only?

### ISSUE THREAD

**Issue by ucy74** [hamuchiwa/AutoRCCar#4]
Why You divide software to three platforms?
Raspberry can drive RC panel like an arduino.
Raspberry can run AI with native video/sonar calc too - no ext streaming.
Is this question of general Raspberry processor speed?

**Comment by hamuchiwa** [comment]
Back then I used a Raspberry Pi model B+, I had to shrink the resolution to 320x240 to achieve "low" latency streaming. With the newer model, it may be possible to do all pieces on Raspberry pi. Another reason is majorly because it's so much easier and more efficient to write/test code on laptop. 
If you have a Raspberry Pi only version, please make a pull request. I'm sure everyone would love to see it. Thanks~

**Comment by jithendran1309** [comment]
why i cannot use raspberry pi for control also
